version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: 87654321
      POSTGRES_DB: dbgis
    ports:
      - 5432:5432
    networks:
      - postgres-net

  #  postgis:
  #    image: postgis/postgis:15-3.3
  #    container_name: postgis-container
  #    environment:
  #      POSTGRES_USER: usuario
  #      POSTGRES_PASSWORD: senha
  #      POSTGRES_DB: banco-espacial
  #    ports:
  #      - 5432:5432
  #    networks:
  #      - postgres-net


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "yuriluiz557@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: 12345678
    ports:
      - 8081:80
    networks:
      - postgres-net

networks:
  postgres-net:
    name: postgres-net


#version: "3.8"
#services:
#  oracle:
#    image: marciokleber/oracle-ee-12c:1.0
#    container_name: oracle
#    volumes:
#      - ./src/main/resources/oracle:/opt/oracle/scripts/startup
#    ports:
#      - 1521:1521
